[2024-03-03T00:02:41.755+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_analyzer.insert_irctc_data_into_db scheduled__2024-03-02T00:00:00+00:00 [queued]>
[2024-03-03T00:02:41.765+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_analyzer.insert_irctc_data_into_db scheduled__2024-03-02T00:00:00+00:00 [queued]>
[2024-03-03T00:02:41.766+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-03T00:02:41.790+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): insert_irctc_data_into_db> on 2024-03-02 00:00:00+00:00
[2024-03-03T00:02:41.798+0000] {standard_task_runner.py:60} INFO - Started process 72 to run task
[2024-03-03T00:02:41.804+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_analyzer', 'insert_irctc_data_into_db', 'scheduled__2024-03-02T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/stock-analyzer.py', '--cfg-path', '/tmp/tmpw8x5kpwb']
[2024-03-03T00:02:41.807+0000] {standard_task_runner.py:88} INFO - Job 247: Subtask insert_irctc_data_into_db
[2024-03-03T00:02:41.871+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_analyzer.insert_irctc_data_into_db scheduled__2024-03-02T00:00:00+00:00 [running]> on host 0a26efe0197d
[2024-03-03T00:02:41.991+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='root' AIRFLOW_CTX_DAG_ID='stock_analyzer' AIRFLOW_CTX_TASK_ID='insert_irctc_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-02T00:00:00+00:00'
[2024-03-03T00:02:41.996+0000] {logging_mixin.py:188} INFO - ['2024-03-01', '934.95', '938.15', '927.0', '929.05', '57727.0']
[2024-03-03T00:02:42.018+0000] {base.py:83} INFO - Using connection ID 'psql-aiven' for task execution.
[2024-03-03T00:02:42.310+0000] {sql.py:457} INFO - Running statement: 
                INSERT INTO irctc_stock_data (date, open, high, low, close, volume) VALUES (%s, %s, %s, %s, %s, %s)
            , parameters: ['2024-03-01', '934.95', '938.15', '927.0', '929.05', '57727.0']
[2024-03-03T00:02:42.342+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock-analyzer.py", line 110, in insert_irctc_data_into_db
    insert_data_into_db(data_file_path, table_name)
  File "/opt/airflow/dags/stock-analyzer.py", line 81, in insert_data_into_db
    postgres_hook.run(insert_stmt, autocommit=True, parameters=outer_list)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 460, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedTable: relation "irctc_stock_data" does not exist
LINE 2:                 INSERT INTO irctc_stock_data (date, open, hi...
                                    ^

[2024-03-03T00:02:42.383+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=stock_analyzer, task_id=insert_irctc_data_into_db, execution_date=20240302T000000, start_date=20240303T000241, end_date=20240303T000242
[2024-03-03T00:02:42.435+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 247 for task insert_irctc_data_into_db (relation "irctc_stock_data" does not exist
LINE 2:                 INSERT INTO irctc_stock_data (date, open, hi...
                                    ^
; 72)
[2024-03-03T00:02:42.457+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-03T00:02:42.478+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
